
version: 2

models:
  - name: silver_reviews
    description: Data dos reviews em cada acomodação
    columns:
      - name: date
        description: "Data em que o review aconteceu, no formato yyyy-mm-dd"
      - name: listing_id
        description: "ID da acomodação, usado para fazer join com a tabela silver_listings"